### ISSUE TITLE
Creatine and Albumine features are from urine not blood

### ISSUE THREAD

**Issue by mdmittriy** [mdmittriy/AgingClock#17]

**Comment by NivedhaBalakrishnan** [comment]
Yes, Creatine and Albumin are from urine. standard biochemistry profile includes results from both urine and blood tests.

**Comment by mdmittriy** [comment]
I see, it looks like at www.aging.ai they use Creatine and Albumin from blood not urine (please double check me on this). And if it's the case let's also stick with only blood biomarkers, meaning we have to change the csv dataset.

**Comment by mdmittriy** [comment]
Fixed by Nivi's pull request #23
